### ISSUE TITLE
Non-consecutive added token '<unk>' found Error

### ISSUE THREAD

**Issue by mbaloch** [ECOFRI/CXR_LLaVA#2]
I am getting errors while try running the model using the transformer. The error stems from tokenization_utils_base.py.
`ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.`

**Comment by ECOFRI** [comment]
Can you tell me the version of transformers package?

This code should work with packages in “requirements.txt”.

**Comment by mbaloch** [comment]
You are right, That was a Transformers package version issue, and I fixed it. Now I am getting this error.
`RuntimeError: cutlassF: no kernel found to launch!`

**Comment by ECOFRI** [comment]
I believe the issue might be associated with PyTorch or CUDA.

Can you run any other model, such as LLAMA2?

You need NVIDIA GPU and appropriate PyTorch version.

**Comment by mbaloch** [comment]
Yes, I can run LLAMA2 in the same environment.

Name: torch
Version: 2.1.2+cu118

**Comment by ECOFRI** [comment]
I was unable to reproduce the error, but you might be interested in the following documents. 
https://github.com/Lightning-AI/lit-gpt/issues/327

In particular, there are reports that performing the code below works without any issues.

```
torch.backends.cuda.enable_mem_efficient_sdp(False)
torch.backends.cuda.enable_flash_sdp(False)
```
I am using NVIDIA A100 and RTX 3090, and both work without any problems.

**Comment by mbaloch** [comment]
setting 
`torch.backends.cuda.enable_mem_efficient_sdp(False)
torch.backends.cuda.enable_flash_sdp(False)`
Fixed the issue. Thank you
