### ISSUE TITLE
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

### ISSUE THREAD

**Issue by AmyRaff** [ECOFRI/CXR_LLaVA#5]
Hi, when I try to use CXR-LLaVA on the Radiologist App I get the following error:

NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

Is this an issue on my end or yours? Cheers.

**Comment by ECOFRI** [comment]
Hi!

The error you saw, "NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH TH
IS PAGE," was likely on my end, not yours. The GPU overheated and caused the process to shut down. I’ve restarted everything, and it should be working fine now.

Thanks for letting me know!
